// All 6 SOP phases - prerequisites, procedures, documentation, gates, signatures
export const SOP_PHASES = [
  {
    id: 'phase1', number: 1, title: 'Pre-Deployment Engagement',
    owner: 'CSM', support: 'PM',
    objective: 'Establish the strategic and operational foundation for the entire deployment. Align with the client on goals, environment, timeline, and requirements — and gather everything the deployment team needs to plan and execute a successful on-site assessment in Phase 2.',
    prerequisites: [
      { id: 'p1_pr1', text: 'Phase 0 Gate is signed off by both the Sales Lead and the CSM.' },
      { id: 'p1_pr2', text: 'Key Contacts form has been received from the client with all required property contacts identified.' },
      { id: 'p1_pr3', text: 'Phase 1 kickoff call is scheduled and confirmed on all parties\' calendars.' },
      { id: 'p1_pr4', text: 'Property-level meeting invites have been prepared and sent, including the Phase 1 preparation guide for each location.' },
      { id: 'p1_pr5', text: 'CSM has reviewed the Commercial Terms Verification Checklist (Phase 0) and is fully briefed on all SLA terms, KPIs, and deal-specific commitments.' },
      { id: 'p1_pr6', text: 'Internal systems confirmed ready — ticketing system, AI Orchestrator, and Call Center updated with client account details.' },
      { id: 'p1_pr7', text: 'OEM documentation on hand — manuals, procedures, and schematics available to the deployment team.' },
    ],
    procedure: [
      { id: 'p1_pc1', text: 'Conduct the Phase 1 Kickoff Call — CSM leads, PM attends to capture notes.' },
      { id: 'p1_pc2', text: 'Confirm Technology Access Requirements — Wi-Fi, cellular, portal users, IT approvals.' },
      { id: 'p1_pc3', text: 'Confirm Deployment Timeline & Scheduling Constraints — preferred start date, blackout periods, Phase 2 assessment date.' },
      { id: 'p1_pc4', text: 'Request Personnel List — names, titles, contacts, shifts, day-to-day POC.' },
      { id: 'p1_pc5', text: 'Confirm Staging Area Requirements — physical location, access, security.' },
      { id: 'p1_pc6', text: 'Prepare and Distribute Property Meeting Invites (multi-property).' },
      { id: 'p1_pc7', text: 'Conduct Property Introduction Meetings (multi-property).' },
    ],
    documentation: [
      { id: 'p1_d1', text: 'Kickoff call notes — decisions, confirmations, action items documented.' },
      { id: 'p1_d2', text: 'Kickoff call notes distributed to all attendees within 24 hours.' },
      { id: 'p1_d3', text: 'Personnel list received from client and filed.' },
      { id: 'p1_d4', text: 'Preliminary deployment timeline documented.' },
      { id: 'p1_d5', text: 'Technology access requirements documented.' },
      { id: 'p1_d6', text: 'Staging area confirmed and documented for each location.' },
      { id: 'p1_d7', text: 'Property-level meeting notes completed (multi-property accounts).' },
      { id: 'p1_d8', text: 'Deployment checklist initiated.' },
      { id: 'p1_d9', text: 'Internal systems updated with Phase 1 information.' },
      { id: 'p1_d10', text: 'Phase 2 on-site assessment visit scheduled and confirmed.' },
    ],
    phaseGate: [
      { id: 'p1_g1', text: 'All Phase 1 Prerequisites confirmed met.' },
      { id: 'p1_g2', text: 'Initial stakeholder kickoff call completed and notes distributed.' },
      { id: 'p1_g3', text: 'Personnel list received from client.' },
      { id: 'p1_g4', text: 'Technology access requirements confirmed and documented.' },
      { id: 'p1_g5', text: 'Preliminary deployment timeline documented.' },
      { id: 'p1_g6', text: 'Staging area confirmed and documented for each property.' },
      { id: 'p1_g7', text: 'Property-level introduction meetings completed.' },
      { id: 'p1_g8', text: 'All documentation items marked complete.' },
      { id: 'p1_g9', text: 'Phase 2 on-site assessment scheduled and confirmed.' },
      { id: 'p1_g10', text: 'Client informed of what to prepare for Phase 2.' },
    ],
    signatures: [
      { id: 'p1_s1', label: 'CSM Sign-Off' },
      { id: 'p1_s2', label: 'PM Sign-Off' },
    ],
  },
  {
    id: 'phase2', number: 2, title: 'On-Site Assessment & Planning',
    owner: 'CSM / Deployment Technician', support: 'PM',
    objective: 'Put eyes on the ground. Conduct a thorough on-site assessment of every deployment location and produce a tailored Deployment Proposal signed by the Client Executive Sponsor before Phase 3 begins.',
    prerequisites: [
      { id: 'p2_pr1', text: 'Phase 1 Gate signed off by both the CSM and PM.' },
      { id: 'p2_pr2', text: 'Phase 2 on-site assessment visit scheduled and confirmed.' },
      { id: 'p2_pr3', text: 'Client Supervisor confirmed as on-site point of contact.' },
      { id: 'p2_pr4', text: 'Personnel list received and filed from Phase 1.' },
      { id: 'p2_pr5', text: 'Technology access requirements documented from Phase 1.' },
      { id: 'p2_pr6', text: 'Staging area location communicated to MBody team.' },
      { id: 'p2_pr7', text: 'Client informed of what to prepare for the visit.' },
      { id: 'p2_pr8', text: 'Visit logistics confirmed — travel, accommodation, technician availability.' },
      { id: 'p2_pr9', text: 'Assessment toolkit prepared — measurement tools, Wi-Fi testing, camera.' },
    ],
    procedure: [
      { id: 'p2_pc1', text: 'Conduct Facility Walkthrough with Client Supervisor.' },
      { id: 'p2_pc2', text: 'Assess and Confirm Docking Station Placement.' },
      { id: 'p2_pc3', text: 'Confirm Staging Area In Person.' },
      { id: 'p2_pc4', text: 'Assess Wi-Fi Signal Strength at All Deployment Locations.' },
      { id: 'p2_pc5', text: 'Identify No-Go Zones and Navigation Obstacles.' },
      { id: 'p2_pc6', text: 'Develop the Tailored Deployment Proposal.' },
      { id: 'p2_pc7', text: 'Present Deployment Proposal to Client Executive Sponsor.' },
      { id: 'p2_pc8', text: 'Obtain formal written sign-off on the Deployment Proposal.' },
      { id: 'p2_pc9', text: 'Initiate Phase 3 Logistics Plan.' },
    ],
    documentation: [
      { id: 'p2_d1', text: 'Site walkthrough notes documented.' },
      { id: 'p2_d2', text: 'Facility photographs filed and organized by area.' },
      { id: 'p2_d3', text: 'Docking station placement plan documented with photographs.' },
      { id: 'p2_d4', text: 'No-go zones and navigation obstacles documented.' },
      { id: 'p2_d5', text: 'Wi-Fi signal strength assessment results documented.' },
      { id: 'p2_d6', text: 'Connectivity action items documented and assigned.' },
      { id: 'p2_d7', text: 'Staging area confirmation documented.' },
      { id: 'p2_d8', text: 'Deployment Proposal completed and presented.' },
      { id: 'p2_d9', text: 'Client Executive Sponsor sign-off on Deployment Proposal obtained.' },
      { id: 'p2_d10', text: 'Phase 3 logistics plan initiated.' },
      { id: 'p2_d11', text: 'Deployment checklist updated.' },
      { id: 'p2_d12', text: 'Client action items documented with owners and deadlines.' },
    ],
    phaseGate: [
      { id: 'p2_g1', text: 'All Phase 2 Prerequisites confirmed met.' },
      { id: 'p2_g2', text: 'On-site facility walkthrough completed at all deployment locations.' },
      { id: 'p2_g3', text: 'Docking station placement confirmed and documented for all units.' },
      { id: 'p2_g4', text: 'No-go zones and navigation obstacles identified and documented.' },
      { id: 'p2_g5', text: 'Wi-Fi signal assessment completed.' },
      { id: 'p2_g6', text: 'Staging area physically confirmed.' },
      { id: 'p2_g7', text: 'Deployment Proposal signed off by Client Executive Sponsor.' },
      { id: 'p2_g8', text: 'All documentation items marked complete.' },
      { id: 'p2_g9', text: 'Phase 3 logistics plan initiated.' },
      { id: 'p2_g10', text: 'All client action items assigned with deadlines.' },
    ],
    signatures: [
      { id: 'p2_s1', label: 'CSM Sign-Off' },
      { id: 'p2_s2', label: 'PM Sign-Off' },
      { id: 'p2_s3', label: 'Client Executive Sponsor Sign-Off' },
    ],
  },
  {
    id: 'phase3', number: 3, title: 'Deployment Logistics & Equipment Preparation',
    owner: 'Deployment Technician', support: 'PM / CSM',
    objective: 'Receive, inspect, verify, and prepare every unit individually before it touches the operational floor. No unit moves to its location without passing every check.',
    prerequisites: [
      { id: 'p3_pr1', text: 'Phase 2 Gate signed off by CSM and PM.' },
      { id: 'p3_pr2', text: 'Deployment Proposal signed off by Client Executive Sponsor.' },
      { id: 'p3_pr3', text: 'Equipment order confirmed with manufacturer.' },
      { id: 'p3_pr4', text: 'Estimated delivery date confirmed.' },
      { id: 'p3_pr5', text: 'Delivery address confirmed — matches staging area.' },
      { id: 'p3_pr6', text: 'Staging area confirmed ready.' },
      { id: 'p3_pr7', text: 'Deployment Technician confirmed available.' },
      { id: 'p3_pr8', text: 'SIM card ordering or activation initiated.' },
      { id: 'p3_pr9', text: 'Consumables inventory confirmed.' },
      { id: 'p3_pr10', text: 'Component quality pre-check inventory confirmed.' },
      { id: 'p3_pr11', text: 'Client completed pre-delivery action items.' },
      { id: 'p3_pr12', text: 'OEM documentation on hand.' },
    ],
    procedure: [
      { id: 'p3_pc1', text: 'Receive and Count All Incoming Units Against Order Manifest.' },
      { id: 'p3_pc2', text: 'Unpack and Conduct Physical Inspection of Every Unit.' },
      { id: 'p3_pc3', text: 'Assess Front Wheel Assemblies on Every Unit.' },
      { id: 'p3_pc4', text: 'Assess Brush Bearing Plates on Every Unit (L50).' },
      { id: 'p3_pc5', text: 'Log All Component Replacements for Warranty Claim Record.' },
      { id: 'p3_pc6', text: 'Power On and Initial Activation of Every Unit.' },
      { id: 'p3_pc7', text: 'Charge Every Unit to 100% Before Verification.' },
      { id: 'p3_pc8', text: 'Verify Every Unit Across All Platforms.' },
      { id: 'p3_pc9', text: 'Conduct Pre-Deployment Systems Check on Every Unit.' },
      { id: 'p3_pc10', text: 'Install Docking Stations at Confirmed Locations.' },
      { id: 'p3_pc11', text: 'Move Verified Units to Designated Operational Locations.' },
    ],
    documentation: [
      { id: 'p3_d1', text: 'Equipment Receiving Checklist completed for every unit.' },
      { id: 'p3_d2', text: 'Serial numbers for all units recorded and filed.' },
      { id: 'p3_d3', text: 'Component quality pre-check completed and documented.' },
      { id: 'p3_d4', text: 'All component replacements logged.' },
      { id: 'p3_d5', text: 'Before/after photographs filed for all component replacements.' },
      { id: 'p3_d6', text: 'Charge time recorded per unit.' },
      { id: 'p3_d7', text: 'Platform verification confirmed for all units.' },
      { id: 'p3_d8', text: 'Docking station installation confirmed and documented.' },
      { id: 'p3_d9', text: 'Unit final placement locations documented by serial number.' },
      { id: 'p3_d10', text: 'Client Supervisor sign-off on unit placement obtained.' },
      { id: 'p3_d11', text: 'Any delivery discrepancies documented with resolution status.' },
      { id: 'p3_d12', text: 'Phase 4 configuration schedule confirmed.' },
    ],
    phaseGate: [
      { id: 'p3_g1', text: 'All Phase 3 Prerequisites confirmed met.' },
      { id: 'p3_g2', text: 'All units received, counted, and serial numbers recorded.' },
      { id: 'p3_g3', text: 'Physical inspection completed on every unit.' },
      { id: 'p3_g4', text: 'Component quality pre-check completed on every unit.' },
      { id: 'p3_g5', text: 'All component replacements documented with photographs.' },
      { id: 'p3_g6', text: 'All units fully charged and within acceptable range.' },
      { id: 'p3_g7', text: 'All units verified across all platforms.' },
      { id: 'p3_g8', text: 'Pre-deployment systems check completed on every unit.' },
      { id: 'p3_g9', text: 'Docking stations installed at all designated locations.' },
      { id: 'p3_g10', text: 'All units moved to operational locations and docked successfully.' },
      { id: 'p3_g11', text: 'Client Supervisor confirmed unit placement.' },
      { id: 'p3_g12', text: 'Equipment Receiving Checklist fully completed.' },
      { id: 'p3_g13', text: 'All documentation items marked complete.' },
      { id: 'p3_g14', text: 'Phase 4 mapping and configuration schedule confirmed.' },
    ],
    signatures: [
      { id: 'p3_s1', label: 'Deployment Technician Sign-Off' },
      { id: 'p3_s2', label: 'CSM Sign-Off' },
      { id: 'p3_s3', label: 'PM Sign-Off' },
    ],
  },
  {
    id: 'phase4', number: 4, title: 'System Configuration & Programming',
    owner: 'Deployment Technician', support: 'CSM / PM',
    objective: 'Transform operational units into intelligent, environment-specific cleaning machines. Every map, schedule, and zone configuration is built for this client\'s specific facility. Client Supervisor sign-off is a hard requirement.',
    prerequisites: [
      { id: 'p4_pr1', text: 'Phase 3 Gate signed off by all three roles.' },
      { id: 'p4_pr2', text: 'All units operational at their designated locations.' },
      { id: 'p4_pr3', text: 'All docking stations installed and units docking successfully.' },
      { id: 'p4_pr4', text: 'Connectivity confirmed at all operational locations.' },
      { id: 'p4_pr5', text: 'Client Supervisor scheduled for Phase 4 sessions.' },
      { id: 'p4_pr6', text: 'Phase 4 configuration schedule confirmed with client.' },
      { id: 'p4_pr7', text: 'Floor plans available to the Deployment Technician.' },
      { id: 'p4_pr8', text: 'No-go zones from Phase 2 available as reference.' },
      { id: 'p4_pr9', text: 'Dashboard user accounts created for all client staff.' },
      { id: 'p4_pr10', text: 'Client Supervisor has dashboard orientation.' },
    ],
    procedure: [
      { id: 'p4_pc1', text: 'Create Detailed Floor Maps for Every Cleaning Zone.' },
      { id: 'p4_pc2', text: 'Define and Program All No-Go Zones.' },
      { id: 'p4_pc3', text: 'Validate Navigation and Obstacle Avoidance in Every Zone.' },
      { id: 'p4_pc4', text: 'Address Navigation Issues and Re-Validate.' },
      { id: 'p4_pc5', text: 'Program Initial Cleaning Schedules with Client Supervisor.' },
      { id: 'p4_pc6', text: 'Conduct Scheduled Run Test.' },
      { id: 'p4_pc7', text: 'Configure Dashboard for Client Environment.' },
      { id: 'p4_pc8', text: 'Confirm User Access and Permissions for All Staff.' },
      { id: 'p4_pc9', text: 'Conduct Formal Map Review Session with Client Supervisor.' },
      { id: 'p4_pc10', text: 'Obtain Formal Written Sign-Off on All Maps.' },
    ],
    documentation: [
      { id: 'p4_d1', text: 'All maps completed, saved, and labeled.' },
      { id: 'p4_d2', text: 'No-go zones programmed and confirmed.' },
      { id: 'p4_d3', text: 'New no-go zones documented with reason.' },
      { id: 'p4_d4', text: 'Navigation validation completed for every zone.' },
      { id: 'p4_d5', text: 'Cleaning schedules programmed and confirmed.' },
      { id: 'p4_d6', text: 'Dashboard configured.' },
      { id: 'p4_d7', text: 'All client staff portal accounts active.' },
      { id: 'p4_d8', text: 'Map Sign-Off Record signed for every unit/zone.' },
      { id: 'p4_d9', text: 'Phase 5 training schedule confirmed.' },
      { id: 'p4_d10', text: 'Deployment checklist updated.' },
    ],
    phaseGate: [
      { id: 'p4_g1', text: 'All Phase 4 Prerequisites confirmed met.' },
      { id: 'p4_g2', text: 'All maps completed for every zone on every unit.' },
      { id: 'p4_g3', text: 'All no-go zones programmed and validated.' },
      { id: 'p4_g4', text: 'Navigation validation completed and issues resolved.' },
      { id: 'p4_g5', text: 'Cleaning schedules programmed and confirmed.' },
      { id: 'p4_g6', text: 'Dashboard fully configured.' },
      { id: 'p4_g7', text: 'All client staff portal accounts active.' },
      { id: 'p4_g8', text: 'Map Sign-Off Record signed for every unit and zone.' },
      { id: 'p4_g9', text: 'All documentation items marked complete.' },
      { id: 'p4_g10', text: 'Phase 5 training schedule confirmed.' },
    ],
    signatures: [
      { id: 'p4_s1', label: 'Deployment Technician Sign-Off' },
      { id: 'p4_s2', label: 'CSM Sign-Off' },
      { id: 'p4_s3', label: 'PM Sign-Off' },
      { id: 'p4_s4', label: 'Client Supervisor Sign-Off' },
    ],
  },
  {
    id: 'phase5', number: 5, title: 'Client Training & Enablement',
    owner: 'CSM / Deployment Technician', support: 'PM',
    objective: 'Equip every person who will interact with the system with the knowledge and confidence to operate it independently. Role-based training for Supervisors and Operators.',
    prerequisites: [
      { id: 'p5_pr1', text: 'Phase 4 Gate signed off.' },
      { id: 'p5_pr2', text: 'All maps validated and Supervisor sign-off complete.' },
      { id: 'p5_pr3', text: 'Dashboard configured and accounts active.' },
      { id: 'p5_pr4', text: 'Training schedule confirmed with all staff.' },
      { id: 'p5_pr5', text: 'Training materials and credentials ready.' },
      { id: 'p5_pr6', text: 'At least one unit available for hands-on practice.' },
    ],
    procedure: [
      { id: 'p5_pc1', text: 'Deliver Supervisor Training Track.' },
      { id: 'p5_pc2', text: 'Deliver Operator Training Track.' },
      { id: 'p5_pc3', text: 'Conduct supervised hands-on practice for all Operators.' },
      { id: 'p5_pc4', text: 'Distribute quick reference guides.' },
      { id: 'p5_pc5', text: 'Confirm portal access for all staff via live login.' },
      { id: 'p5_pc6', text: 'Assess staff confidence and address knowledge gaps.' },
      { id: 'p5_pc7', text: 'Obtain Client Supervisor confirmation of staff readiness.' },
    ],
    documentation: [
      { id: 'p5_d1', text: 'Training Attendance Record signed by all participants.' },
      { id: 'p5_d2', text: 'Quick reference guides distributed.' },
      { id: 'p5_d3', text: 'Portal access confirmed for all staff.' },
      { id: 'p5_d4', text: 'Knowledge gaps documented and addressed.' },
      { id: 'p5_d5', text: 'Client Supervisor readiness confirmation obtained.' },
    ],
    phaseGate: [
      { id: 'p5_g1', text: 'All Phase 5 Prerequisites confirmed met.' },
      { id: 'p5_g2', text: 'Supervisor track delivered.' },
      { id: 'p5_g3', text: 'Operator track delivered with hands-on practice.' },
      { id: 'p5_g4', text: 'Training Attendance Record signed.' },
      { id: 'p5_g5', text: 'Quick reference guides distributed.' },
      { id: 'p5_g6', text: 'Portal access confirmed for all staff.' },
      { id: 'p5_g7', text: 'Knowledge gaps addressed.' },
      { id: 'p5_g8', text: 'Client Supervisor confirms team readiness.' },
    ],
    signatures: [
      { id: 'p5_s1', label: 'CSM Sign-Off' },
      { id: 'p5_s2', label: 'PM Sign-Off' },
      { id: 'p5_s3', label: 'Client Supervisor Sign-Off' },
    ],
  },
  {
    id: 'phase6', number: 6, title: 'Program Launch & Ongoing Partnership',
    owner: 'CSM', support: 'PM',
    objective: 'Part A formally launches the program. Part B defines the ongoing partnership standard. The deployment is the starting line, not the finish line.',
    prerequisites: [
      { id: 'p6_pr1', text: 'Phase 5 Gate signed off.' },
      { id: 'p6_pr2', text: 'All units operational and running autonomously.' },
      { id: 'p6_pr3', text: 'All internal systems fully updated.' },
      { id: 'p6_pr4', text: 'CSM confirmed as primary relationship owner.' },
      { id: 'p6_pr5', text: 'PM visit schedule and reporting cadence established.' },
    ],
    procedure: [
      { id: 'p6_pc1', text: 'PART A: Hold formal program launch meeting with Executive Sponsor.' },
      { id: 'p6_pc2', text: 'PART A: Complete internal deployment close-out.' },
      { id: 'p6_pc3', text: 'PART A: Complete first bi-weekly PM visit and deliver report.' },
      { id: 'p6_pc4', text: 'PART A: Deliver first formal performance report.' },
      { id: 'p6_pc5', text: 'PART B (ongoing): PM visits every two weeks.' },
      { id: 'p6_pc6', text: 'PART B (ongoing): Regular performance reports per cadence.' },
      { id: 'p6_pc7', text: 'PART B (ongoing): Quarterly Business Reviews with Executive Sponsor.' },
      { id: 'p6_pc8', text: 'PART B (ongoing): Proactive optimization.' },
      { id: 'p6_pc9', text: 'PART B (ongoing): Use case expansion conversations.' },
      { id: 'p6_pc10', text: 'PART B (ongoing): Exceed service expectations as standard.' },
    ],
    documentation: [
      { id: 'p6_d1', text: 'Program launch meeting notes filed.' },
      { id: 'p6_d2', text: 'First PM visit report delivered.' },
      { id: 'p6_d3', text: 'First performance report delivered.' },
      { id: 'p6_d4', text: 'Ongoing PM reports filed.' },
      { id: 'p6_d5', text: 'Ongoing performance reports filed.' },
      { id: 'p6_d6', text: 'QBR notes filed.' },
      { id: 'p6_d7', text: 'Optimization log maintained.' },
      { id: 'p6_d8', text: 'SLA compliance log maintained.' },
    ],
    phaseGate: [
      { id: 'p6_g1', text: 'All Phase 6 Prerequisites confirmed met.' },
      { id: 'p6_g2', text: 'Program launch meeting completed.' },
      { id: 'p6_g3', text: 'Internal deployment close-out completed.' },
      { id: 'p6_g4', text: 'First PM visit completed and report delivered.' },
      { id: 'p6_g5', text: 'First performance report delivered.' },
      { id: 'p6_g6', text: 'Ongoing PM visit schedule active.' },
    ],
    signatures: [
      { id: 'p6_s1', label: 'CSM Sign-Off (Part A)' },
      { id: 'p6_s2', label: 'PM Sign-Off (Part A)' },
      { id: 'p6_s3', label: 'Client Executive Sponsor Sign-Off (Part A)' },
    ],
  },
];
